[workspace]
resolver = "2"
members = [
    "kernel-generic-hazard3",
    "tools/build",
    "tools/hubake",
    "tools/alloc",
    "sys/userlib",
    "sys/kipc",
    "sys/num-tasks",
    "task/minisuper",
]

[workspace.dependencies]
userlib = {path = "sys/userlib"}
kipc = {path = "sys/kipc"}
hubris-num-tasks = {path = "sys/num-tasks"}
hubris-build = {path="tools/build"}

[profile.release]
debug = true
lto = true
opt-level = "s"
