[package]
name = "kernel-generic-hazard3"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv = { version = "0.14", features = ["critical-section-single-hart"] }
riscv-rt = { version = "0.15", features = ["device", "memory"] }

[dependencies.rp235x-pac]
package = "rp235x-pac"
path = "../../rp235x-pac"
features = ["rt"]

[dependencies.hubris-kern]
package = "kern"
#git = "https://github.com/Karthik-d-k/hubris-riscv-hazard3"
#branch = "riscv"
path = "../../hubris-riscv-hazard3/sys/kern"
features = ["stack-watermark"]
