[package]
name = "kernel-generic-hazard3"
version = "0.1.0"
edition = "2021"

[target.riscv32imac-unknown-none-elf.dependencies]
riscv = { version = "0.14", features = ["critical-section-single-hart"] }
riscv-rt = { version = "0.15" }
rp235x-pac = {version = "0.1.0", features = ["critical-section", "rt"]}
sha2-const-stable = "0.1"
rp235x-sys = { path = "../drv/rp235x-sys" }
riscv-semihosting = { version = "0.2.0", features = ["default"] }

[dependencies.hubris-kern]
package = "kern"
git = "https://github.com/Karthik-d-k/hubris-riscv-hazard3"
branch = "hazard3"
features = ["dump"]
