[package]
name = "kernel-generic-cortex-m33"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.7"
rp235x-pac = {version = "0.1.0", features = ["rt"]}
sha2-const-stable = "0.1"
#rp-pac = { version = "7.0.0", features = ["rt", "rp235x"] }

[dependencies.hubris-kern]
package = "kern"
#git = "https://github.com/Karthik-d-k/hubris-riscv-hazard3"
#branch = "riscv"
path = "../../hubris-riscv-hazard3/sys/kern"
features = ["stack-watermark"]
